services:
  mud:
    build: .
    ports:
      - "1111:1111"
    volumes:
      - asteria_accounts:/home/asteria/accounts
      - asteria_backup:/home/asteria/backup
      - asteria_log:/home/asteria/log
      - asteria_data:/home/asteria/data
      - asteria_zones:/home/asteria/zones
    deploy:
      restart_policy:
        condition: on-failure
        delay: 0s
        max_attempts: 5
        window: 120s

volumes:
  asteria_accounts:
    external: true
  asteria_backup:
    external: true
  asteria_log:
    external: true
  asteria_data:
    external: true
  asteria_zones:
    external: true