services:
  mud:
    build: .
    ports:
      - "1111:1111"
    working_dir: /home/asteria
    volumes:
      - accounts:/home/asteria/accounts
      - backup:/home/asteria/backup
      - data:/home/asteria/data
      - log:/home/asteria/log

volumes:
  accounts:
  backup:
  data:
  log: